# Exported from Render on 2024-08-29T01:30:07Z
services:
- type: web
  name: Bank-Churn-Prediction-Capstone-Project-
  runtime: python
  repo: https://github.com/NelviusGrey/Bank-Churn-Prediction-Capstone-Project-
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn bank_churn:server
version: "1"
